services:

  graphdb:
    image: graphdb
    container_name: graphdb
    ports:
      - "7200:7200"
    healthcheck:
      test: curl --fail http://localhost:7200/rest/repositories || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  weaviate:
    image: semitechnologies/weaviate:1.22.5
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=''
      - CLUSTER_HOSTNAME=node1
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - AUTOSCHEMA_ENABLED=false
    volumes:
      - ./weaviate:/var/lib/weaviate

  ontotext-embedding:
      image: maven.ontotext.com/embeddings/embeddings-api:1.0.0
      ports:
        - "8081:6000"
      environment:
        - EMBEDDINGS_IMPL=azure-open-ai
        - AZURE_OPENAI_ENDPOINT=https://statnett.openai.azure.com/
        - OPENAI_API_VERSION=2024-02-01
        - AZURE_EMBEDDINGS_MODEL=text-embedding-3-small
        - AZURE_OPENAI_API_KEY=<API_KEY>
      healthcheck:
        test: [ "CMD", "curl", "--fail", "http://localhost:6000/__health" ]
        interval: 30s
        retries: 4
        start_period: 60s
        timeout: 20s

  retrieval-plugin:
      image: maven.ontotext.com/llm/ontotext-llm-retrieval-plugin:1.3.2
      ports:
        - "8082:8080"
      environment:
        - WEAVIATE_INDEXES_NAMES=OpenAIDocument
        - WEAVIATE_UPDATE_SCHEMA_DATA_PROPERTIES_AT_RUNTIME=false
        - EMBEDDINGS_API_URL=http://ontotext-embedding:6000/embeddings
        - BEARER_TOKEN=DUMMY
        - WEAVIATE_HOST=http://weaviate
      healthcheck:
        test: [ "CMD", "curl", "--fail", "http://localhost:8080/__gtg" ]
        interval: 30s
        retries: 4
        start_period: 60s
        timeout: 20s
      depends_on:
        weaviate:
          condition: service_started
        ontotext-embedding:
          condition: service_healthy
