version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(asctime)s] [%(threadName)s] [%(name)s] %(levelname)s - %(x_request_id)s - %(message)s'
filters:
  xRequestIdFilter:
    (): talk2powersystemllm.app.server.x_request_id_logging_filter.XRequestIdFilter
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters: [ xRequestIdFilter ]
loggers:
  uvicorn.error:
    level: INFO
    handlers: [ console ]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [ console ]
    propagate: no
root:
  level: INFO
  handlers: [ console ]
  propagate: no
