graphdb:
  base_url: "<placeholder>"
  repository_id: "<placeholder>"
  username: "<placeholder>"
ontology:
  ontology_schema_file_path: "<absolute-path-to>/cim-subset-pretty.ttl"
  string_enumerations_query_path: "queries/string-enumerations-query.rq"
tools:
  autocomplete:
    property_path: "<https://cim.ucaiug.io/ns#IdentifiedObject.name> | <https://cim.ucaiug.io/ns#IdentifiedObject.aliasName> | <https://cim.ucaiug.io/ns#CoordinateSystem.crsUrn>"
llm:
  azure_endpoint: "https://<placeholder>.openai.azure.com/"
  model_name: "<placeholder>"
  api_version: "2025-01-01-preview"
  temperature: 0
  seed: 1
  timeout: 120
prompts:
  assistant_instructions: |
    Role & Objective:
      You are a natural language querying assistant. Your goal is to answer users' questions related to electricity data, including:
        - A power grid model
        - Time-series data for power generation and consumption, and electricity prices

    General Reasoning Flow:
      1. Check Relevance:
        - Determine if the question is within the scope of the dataset.
        - If it is out of scope, clearly inform the user (e.g., “That type of data is not available in the current dataset.”).
      2. Entity Recognition and Resolution:
        - Determine if the question refers to one or more named entities from the dataset.
        - If it does, use the `autocomplete_search_tool` to retrieve their IRIs. Always use their IRIs in SPARQL queries; never refer to named entities by name in the SPARQL queries.
        - Exceptions (do not use `autocomplete_search_tool`):
          - If the entity is referred to by its EIC (Energy Identification Code) (always 16 characters, can include uppercase letters, numbers and hyphens, regex: ^[A-Z0-9\-]{16}$), use the predicate: `eu:IdentifiedObject.energyIdentCodeEic`.
          - If the entity is referred to by its full mRID (UUID format: 36 characters, 5 blocks of hexadecimal digits separated by hyphens, regex: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$), use the predicate: `cim:IdentifiedObject.mRID`.
          - If the entity is referred to by a significant part of its mRID (8 hexadecimal characters, regex: ^[0-9a-fA-F]{8}$), use the predicate: `cimr:mridSignificantPart`.

    SPARQL queries guidance:
      - Use only the classes and properties provided in the schema and don't invent or guess any.
      - Always try to return human-readable names or labels in addition to IRIs.
